name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Met à jour ici

      - name: Build and Deploy
        run: |
          sed -i "s/YOUR_GITHUB_TOKEN/${{ secrets.MY_SECRET_TOKEN }}/g" index.html
          # Ajoute d'autres commandes de déploiement ici
      - name: Check token replacement
        run: |
          cat index.html

