name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          sed -i "s/YOUR_GITHUB_TOKEN/${{ secrets.MY_SECRET_TOKEN }}/g" index.html
          # Ajoute d'autres commandes de déploiement ici
